### ISSUE TITLE
Application not starting 

### ISSUE THREAD

**Issue by Arcami** [hlung/Hearthstone-Deck-Builder#1]
OS X 10.9.5

There's only the icon on the dock. The application won't start.

I hope we can find a fix because this utility looks amazing =)

**Comment by hlung** [comment]
@Arcami Thanks for reporting! I have made an update to fix a crash bug while exporting. Check out [v0.2 in release page](https://github.com/hlung/Hearthstone-Deck-Builder/releases/tag/v0.2). May be it fixes your issue too. Please try :)

**Comment by hlung** [comment]
v0.3 is also out! Please inform if you still see the problem.

**Comment by hlung** [comment]
No response. Closing issue.
